name = "GesellschaftProtocol"
uuid = "6cd8c5fb-a37a-4af9-9a4a-ee6ea17f9aaa"
authors = ["Syx Pek <20557013+SyxP@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
